---
title: Chris Walter
author: chriswalter.info
email: cwalte12@mail.wvu.edu
description: Landing page for Chris Walter
baseurl: "/ubuild-jekyll"
url: chriswalter.info
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
