# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://chriswalter.ifo
title: Chris Walter
email: christopher.walter@sylvera.io
author: Chris Walter
description: > # "Write an awesome description for your new site here. 
  Chris Walter - Data and Research Scientist.
copyright: 'Copyright &copy; 2022 Chris Walter.'
credits: '2</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: www.linkedin.com/in/chrisalanwalter
  - title: github
    url: https://github.com/waltscience
  - title: mail
    url: mailto:christopher.walter@sylvera.io
